Repository hiero-ledger/hiero-block-node, pull requests merged in 2024-07, with the labels that each got.

#43 CI Test Check for Style guidelines using Spotless plugin
  .github/workflows/spotless-check.yml
Labels: Improvement

#46 Dockerization of Block Node Server
  .gitignore
  server/build.gradle.kts
  server/docker/.dockerignore
  server/docker/Dockerfile
  server/docker/README.md
  server/docker/docker-build.sh
  server/docker/docker-compose.yml
  server/docker/update-env.sh
Labels: Improvement, P2, Release

#48 Release image publish
  .github/workflows/release-push-image.yaml
Labels: Improvement, P2, Release

#51 ci: test check - and pr checks consolidation into single workflow
  .github/workflows/build-application.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/pr-formatting.yaml
  README.md
Labels: Improvement, P2, Release

#26 feat: Added Get Block
  .gitignore
  protos/src/main/protobuf/blockstream.proto
  server/src/main/java/com/hedera/block/server/BlockStreamService.java
  server/src/main/java/com/hedera/block/server/Constants.java
  server/src/main/java/com/hedera/block/server/Server.java
  server/src/test/java/com/hedera/block/server/BlockStreamServiceTest.java
Labels: New Feature, P2

#62 fix: assigne, label and milestone checks
  .github/workflows/pr-formatting.yaml
Labels: Bug

#58 ci: Fix Image publish GHA WF to provide build-arg and build-context to dockerfile.
  .github/workflows/release-push-image.yaml
Labels: Improvement, Release, github_actions

#57 build: Add a new gradle task to start the docker container in debug mode.
  server/build.gradle.kts
  server/docker/update-env.sh
Labels: Improvement

#64 fix: Adding port mapping for debug when available
  server/docker/docker-compose.yml
Labels: Bug

#63 feat: Helm Chart
  .github/workflows/helm-charts.yaml
  charts/.gitignore
  charts/hedera-block-node/.helmignore
  charts/hedera-block-node/Chart.yaml
  charts/hedera-block-node/README.md
  charts/hedera-block-node/templates/NOTES.txt
  charts/hedera-block-node/templates/_helpers.tpl
  charts/hedera-block-node/templates/configmap.yaml
  charts/hedera-block-node/templates/deployment.yaml
  charts/hedera-block-node/templates/ingress.yaml
  charts/hedera-block-node/templates/secret.yaml
  charts/hedera-block-node/templates/service.yaml
  charts/hedera-block-node/templates/serviceaccount.yaml
  charts/hedera-block-node/values.yaml
  ct.yaml
Labels: P2, Release, github_actions
