Repository hiero-ledger/hiero-block-node, pull requests merged in 2024-08, with the labels that each got.

#83 fix: upgraded gradlew to 8.8 to match services and fix 00081
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  protos/src/test/java/module-info.java
Labels: Bug

#87 feat: Add SpotBugs Annotation
  buildSrc/src/main/kotlin/com.hedera.block.jpms-modules.gradle.kts
  server/src/main/java/module-info.java
  settings.gradle.kts
Labels: dependencies

#90 feat: added annotations for tests to use
  server/build.gradle.kts
Labels: dependencies

#88 test: Override configs for CodeCov, using yml file at project root
  codecov.yml
Labels: Improvement

#92 chore: upgraded Helidon to 4.0.11
  settings.gradle.kts
Labels: dependencies

#41 refactor: 00029 refactor demo to lmax disruptor and 00055 persistence design doc
  gradle/modules.properties
  protos/src/main/protobuf/blockstream.proto
  server/docker/Dockerfile
  server/docker/docker-compose.yml
  server/docs/design/block-persistence.md
  server/src/main/java/com/hedera/block/server/BlockStreamService.java
  server/src/main/java/com/hedera/block/server/Constants.java
  server/src/main/java/com/hedera/block/server/Server.java
  server/src/main/java/com/hedera/block/server/ServiceStatus.java
  server/src/main/java/com/hedera/block/server/ServiceStatusImpl.java
  server/src/main/java/com/hedera/block/server/config/BlockNodeContextFactory.java
  server/src/main/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserver.java
  server/src/main/java/com/hedera/block/server/consumer/LiveStreamObserver.java
  server/src/main/java/com/hedera/block/server/consumer/LiveStreamObserverImpl.java
  server/src/main/java/com/hedera/block/server/data/ObjectEvent.java
  server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorBuilder.java
  server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorImpl.java
  server/src/main/java/com/hedera/block/server/mediator/Publisher.java
  server/src/main/java/com/hedera/block/server/mediator/SubscriptionHandler.java
  server/src/main/java/com/hedera/block/server/metrics/MetricsService.java
  server/src/main/java/com/hedera/block/server/persistence/BlockPersistenceHandler.java
  server/src/main/java/com/hedera/block/server/persistence/WriteThroughCacheHandler.java
  server/src/main/java/com/hedera/block/server/persistence/storage/FileSystemBlockStorage.java
  server/src/main/java/com/hedera/block/server/persistence/storage/Util.java
  server/src/main/java/com/hedera/block/server/persistence/storage/read/BlockAsDirReader.java
  server/src/main/java/com/hedera/block/server/persistence/storage/read/BlockAsDirReaderBuilder.java
  server/src/main/java/com/hedera/block/server/persistence/storage/read/BlockReader.java
  server/src/main/java/com/hedera/block/server/persistence/storage/remove/BlockAsDirRemover.java
  server/src/main/java/com/hedera/block/server/persistence/storage/remove/BlockRemover.java
  server/src/main/java/com/hedera/block/server/persistence/storage/write/BlockAsDirWriter.java
  server/src/main/java/com/hedera/block/server/persistence/storage/write/BlockAsDirWriterBuilder.java
  server/src/main/java/com/hedera/block/server/persistence/storage/write/BlockWriter.java
  server/src/main/java/com/hedera/block/server/producer/ItemAckBuilder.java
  server/src/main/java/com/hedera/block/server/producer/ProducerBlockItemObserver.java
  server/src/main/java/com/hedera/block/server/producer/ProducerBlockStreamObserver.java
  server/src/main/java/com/hedera/block/server/producer/Util.java
  server/src/main/java/module-info.java
  server/src/test/java/com/hedera/block/server/BlockStreamServiceIT.java
  server/src/test/java/com/hedera/block/server/BlockStreamServiceTest.java
  server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java
  server/src/test/java/com/hedera/block/server/consumer/LiveStreamObserverImplTest.java
  server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
  server/src/test/java/com/hedera/block/server/persistence/PersistTestUtils.java
  server/src/test/java/com/hedera/block/server/persistence/RangeTest.java
  server/src/test/java/com/hedera/block/server/persistence/WriteThroughCacheHandlerTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/read/BlockAsDirReaderTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/remove/BlockAsDirRemoverTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/write/BlockAsDirWriterTest.java
  server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java
  server/src/test/java/com/hedera/block/server/util/PersistTestUtils.java
  server/src/test/java/com/hedera/block/server/util/TestUtils.java
  server/src/test/resources/consumer.sh
  server/src/test/resources/producer.sh
  settings.gradle.kts
Labels: Epic

#97 feat: Grafana Initial Dashboard and Dev Env for Metrics
  server/docker/docker-compose.yml
  server/docker/metrics/dashboards/block-node-server.json
  server/docker/metrics/dashboards/provisioner.yaml
  server/docker/metrics/datasources/datasources.yml
  server/docker/metrics/prometheus.yml
  server/docs/metrics.md
  server/src/main/java/com/hedera/block/server/Server.java
  server/src/main/java/com/hedera/block/server/config/BlockNodeContextFactory.java
  server/src/main/java/com/hedera/block/server/metrics/MetricsService.java
  server/src/test/java/com/hedera/block/server/metrics/MetricsServiceTest.java
Labels: Improvement, P2

#100 fix: removed commented out code
  server/src/main/java/com/hedera/block/server/BlockStreamService.java
Labels: Bug

#101 refactor: configuration to use Platform SDK across all project
  .gitignore
  README.md
  server/src/main/java/com/hedera/block/server/BlockStreamService.java
  server/src/main/java/com/hedera/block/server/Constants.java
  server/src/main/java/com/hedera/block/server/Server.java
  server/src/main/java/com/hedera/block/server/config/BlockNodeConfigExtension.java
  server/src/main/java/com/hedera/block/server/consumer/ConsumerConfig.java
  server/src/main/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserver.java
  server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorImpl.java
  server/src/main/java/com/hedera/block/server/persistence/storage/FileUtils.java
  server/src/main/java/com/hedera/block/server/persistence/storage/PersistenceStorageConfig.java
  server/src/main/java/com/hedera/block/server/persistence/storage/read/BlockAsDirReader.java
  server/src/main/java/com/hedera/block/server/persistence/storage/read/BlockAsDirReaderBuilder.java
  server/src/main/java/com/hedera/block/server/persistence/storage/write/BlockAsDirWriter.java
  server/src/main/java/com/hedera/block/server/persistence/storage/write/BlockAsDirWriterBuilder.java
  server/src/main/java/module-info.java
  server/src/main/resources/application.yaml
  server/src/test/java/com/hedera/block/server/BlockStreamServiceIT.java
  server/src/test/java/com/hedera/block/server/BlockStreamServiceTest.java
  server/src/test/java/com/hedera/block/server/config/TestConfigBuilder.java
  server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java
  server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/PersistenceStorageConfigTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/read/BlockAsDirReaderTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/remove/BlockAsDirRemoverTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/write/BlockAsDirWriterTest.java
  server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java
  server/src/test/java/com/hedera/block/server/util/TestConfigUtil.java
  server/src/test/resources/app.properties
Labels: Improvement

#102 chore: Update SECURITY.md
  SECURITY.md
Labels: Improvement, P2

#103 fix: fix config exports
  server/src/main/java/module-info.java
Labels: Bug

#112 ci: update self hosted runner label and codeowners
  .github/CODEOWNERS
  .github/workflows/pr-checks.yaml
  .github/workflows/pr-formatting.yaml
  .github/workflows/release-push-image.yaml
Labels: P0

#111 feat: Health endpoints
  charts/hedera-block-node/templates/deployment.yaml
  charts/hedera-block-node/values.yaml
  server/src/main/java/com/hedera/block/server/Server.java
  server/src/main/java/com/hedera/block/server/health/HealthService.java
  server/src/main/java/com/hedera/block/server/health/HealthServiceImpl.java
  server/src/main/java/module-info.java
  server/src/test/java/com/hedera/block/server/health/HealthServiceTest.java
Labels: Improvement

#117 feat: 00071 hedera protobufs
  .gitignore
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Utils.kt
  buildSrc/src/main/kotlin/com.hedera.block.jpms-modules.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.block.protobuf.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.block.spotless-java-conventions.gradle.kts
  buildSrc/src/main/kotlin/com/hedera/block/tasks/GitClone.kt
  codecov.yml
  gradle/modules.properties
  protos/build.gradle.kts
  protos/src/main/java/module-info.java
  protos/src/main/protobuf/blockstream.proto
  server/build.gradle.kts
  server/src/main/java/com/hedera/block/server/BlockStreamService.java
  server/src/main/java/com/hedera/block/server/Constants.java
  server/src/main/java/com/hedera/block/server/Server.java
  server/src/main/java/com/hedera/block/server/Translator.java
  server/src/main/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserver.java
  server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorBuilder.java
  server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorImpl.java
  server/src/main/java/com/hedera/block/server/persistence/storage/FileUtils.java
  server/src/main/java/com/hedera/block/server/persistence/storage/PersistenceStorageConfig.java
  server/src/main/java/com/hedera/block/server/persistence/storage/read/BlockAsDirReader.java
  server/src/main/java/com/hedera/block/server/persistence/storage/read/BlockAsDirReaderBuilder.java
  server/src/main/java/com/hedera/block/server/persistence/storage/read/BlockReader.java
  server/src/main/java/com/hedera/block/server/persistence/storage/remove/BlockAsDirRemover.java
  server/src/main/java/com/hedera/block/server/persistence/storage/write/BlockAsDirWriter.java
  server/src/main/java/com/hedera/block/server/persistence/storage/write/BlockAsDirWriterBuilder.java
  server/src/main/java/com/hedera/block/server/producer/ItemAckBuilder.java
  server/src/main/java/com/hedera/block/server/producer/ProducerBlockItemObserver.java
  server/src/main/java/com/hedera/block/server/producer/Util.java
  server/src/main/java/module-info.java
  server/src/test/java/com/hedera/block/server/BlockStreamServiceIntegrationTest.java
  server/src/test/java/com/hedera/block/server/BlockStreamServiceTest.java
  server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java
  server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/read/BlockAsDirReaderTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/remove/BlockAsDirRemoverTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/write/BlockAsDirWriterTest.java
  server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java
  server/src/test/java/com/hedera/block/server/util/PersistTestUtils.java
  server/src/test/resources/batch_consumer.sh
  server/src/test/resources/block_service.proto
  server/src/test/resources/consumer.sh
  server/src/test/resources/producer.sh
  server/src/test/resources/templates/block_proof_template.json
  server/src/test/resources/templates/event_template.json
  server/src/test/resources/templates/header_template.json
  settings.gradle.kts
  stream/build.gradle.kts
  stream/src/main/java/module-info.java
Labels: Improvement, P1, Epic

#113 test: Smoke test
  .github/workflows/helm-charts.yaml
  .github/workflows/smoke-test.yaml
  server/src/test/resources/get-block.sh
  server/src/test/resources/smoke-test.sh
Labels: P1

#118 feat: Add Dagger for Dependency Injection Framework
  buildSrc/src/main/kotlin/com.hedera.block.jpms-modules.gradle.kts
  gradle/modules.properties
  server/build.gradle.kts
  server/src/main/java/com/hedera/block/server/BlockNodeApp.java
  server/src/main/java/com/hedera/block/server/BlockNodeAppInjectionComponent.java
  server/src/main/java/com/hedera/block/server/BlockNodeAppInjectionModule.java
  server/src/main/java/com/hedera/block/server/Server.java
  server/src/main/java/com/hedera/block/server/ServiceStatusImpl.java
  server/src/main/java/com/hedera/block/server/health/HealthInjectionModule.java
  server/src/main/java/com/hedera/block/server/health/HealthServiceImpl.java
  server/src/main/java/module-info.java
  server/src/test/java/com/hedera/block/server/BlockNodeAppInjectionModuleTest.java
  settings.gradle.kts
Labels: Improvement

#133 test: Fix smoke test after PBJ Changes were merged and rebased
  server/src/test/resources/get-block.sh
Labels: P1, Tests

#134 feat: Dagger refactor
  server/src/main/java/com/hedera/block/server/BlockNodeApp.java
  server/src/main/java/com/hedera/block/server/BlockNodeAppInjectionComponent.java
  server/src/main/java/com/hedera/block/server/BlockNodeAppInjectionModule.java
  server/src/main/java/com/hedera/block/server/BlockStreamService.java
  server/src/main/java/com/hedera/block/server/Constants.java
  server/src/main/java/com/hedera/block/server/Server.java
  server/src/main/java/com/hedera/block/server/config/BlockNodeConfigExtension.java
  server/src/main/java/com/hedera/block/server/config/BlockNodeContext.java
  server/src/main/java/com/hedera/block/server/config/BlockNodeContextFactory.java
  server/src/main/java/com/hedera/block/server/config/ConfigInjectionModule.java
  server/src/main/java/com/hedera/block/server/health/HealthInjectionModule.java
  server/src/main/java/com/hedera/block/server/mediator/MediatorInjectionModule.java
  server/src/main/java/com/hedera/block/server/metrics/MetricsInjectionModule.java
  server/src/main/java/com/hedera/block/server/persistence/PersistenceInjectionModule.java
  server/src/main/java/module-info.java
  server/src/test/java/com/hedera/block/server/BlockNodeAppInjectionModuleTest.java
  server/src/test/java/com/hedera/block/server/BlockNodeAppTest.java
  server/src/test/java/com/hedera/block/server/config/BlockNodeContextFactoryTest.java
  server/src/test/java/com/hedera/block/server/config/BlockNodeContextTest.java
  server/src/test/java/com/hedera/block/server/config/ConfigInjectionModuleTest.java
  server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
  server/src/test/java/com/hedera/block/server/mediator/MediatorInjectionModuleTest.java
  server/src/test/java/com/hedera/block/server/metrics/MetricsInjectionModuleTest.java
  server/src/test/java/com/hedera/block/server/persistence/PersistenceInjectionModuleTest.java
  server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java
  server/src/test/java/com/hedera/block/server/util/TestConfigUtil.java
Labels: Improvement, P2

#140 fix: Increased testTimeouts to promote test success on GHA runners
  server/src/test/java/com/hedera/block/server/BlockStreamServiceIntegrationTest.java
  server/src/test/java/com/hedera/block/server/BlockStreamServiceTest.java
  server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java
  server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
  server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java
Labels: Bug

#138 chore: upgraded Helidon and its deps to 4.1.0
  gradle/modules.properties
  settings.gradle.kts
Labels: dependencies

#142 refactor: MetricsService refactor to use an interface
  server/src/main/java/com/hedera/block/server/BlockStreamService.java
  server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorImpl.java
  server/src/main/java/com/hedera/block/server/metrics/MetricsInjectionModule.java
  server/src/main/java/com/hedera/block/server/metrics/MetricsService.java
  server/src/main/java/com/hedera/block/server/metrics/MetricsServiceImpl.java
  server/src/main/java/com/hedera/block/server/persistence/storage/write/BlockAsDirWriter.java
  server/src/test/java/com/hedera/block/server/BlockStreamServiceIntegrationTest.java
  server/src/test/java/com/hedera/block/server/config/BlockNodeContextTest.java
  server/src/test/java/com/hedera/block/server/config/TestConfigBuilder.java
  server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
  server/src/test/java/com/hedera/block/server/metrics/MetricsInjectionModuleTest.java
  server/src/test/java/com/hedera/block/server/metrics/MetricsServiceTest.java
  server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java
  server/src/test/java/com/hedera/block/server/util/TestConfigUtil.java
Labels: Improvement, P2

#143 refactor: Healthz endpoints refactor
  charts/hedera-block-node/values.yaml
  server/src/main/java/com/hedera/block/server/health/HealthService.java
  server/src/main/java/com/hedera/block/server/health/HealthServiceImpl.java
  server/src/test/java/com/hedera/block/server/health/HealthServiceTest.java
  server/src/test/resources/smoke-test.sh
Labels: Improvement, P2
