Repository hiero-ledger/hiero-block-node, pull requests merged in 2025-08, with the labels that each got.

#1423 feat: Simulator Support for EndStream Request with Too_Far_Behind. so BN backfills
  docs/simulator/configuration.md
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializer.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/config/data/BlockStreamConfig.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/config/types/EndStreamMode.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/PublishStreamGrpcClient.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImpl.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/mode/impl/PublishClientManager.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/logging/SimulatorConfigurationLoggerTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java
  tools-and-tests/suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java
Labels: pull request

#1451 test: add test for DUPLICATE_BLOCK status with starting block number 0
  tools-and-tests/suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java
Labels: Tests

#1462 fix: Setting property generator.endBlockNumber is not stopping simulator
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/generator/CraftBlockStreamManager.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/CraftBlockStreamManagerTest.java
Labels: pull request

#1460 chore(logging): Improved Logging for debugging and troubleshooting at TRACE level.
  block-node/app/src/main/resources/logging.properties
  block-node/messaging/src/main/java/org/hiero/block/node/messaging/BlockMessagingFacilityImpl.java
  block-node/server-status/src/main/java/org/hiero/block/node/server/status/ServerStatusServicePlugin.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java
  block-node/verification/src/main/java/org/hiero/block/node/verification/VerificationServicePlugin.java
Labels: Improvement, Block Node

#1464 feat: Simulator add publisher support for ResendBlock message
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImpl.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamObserver.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/mode/impl/PublishClientManager.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamObserverTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/mode/PublishClientManagerTest.java
Labels: pull request

#1468 chore(release): Bump versions for v0.17.0-SNAPSHOT
  charts/block-node-server/Chart.yaml
  charts/blockstream-simulator/Chart.yaml
  version.txt
Labels: Release

#1444 feat(backfill): On-Demand Backfilling and other improvements
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/TestBlockMessagingFacility.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/server/TestBlockNodeServer.java
  block-node/backfill/src/main/java/org/hiero/block/node/backfill/BackfillConfiguration.java
  block-node/backfill/src/main/java/org/hiero/block/node/backfill/BackfillGrpcClient.java
  block-node/backfill/src/main/java/org/hiero/block/node/backfill/BackfillPlugin.java
  block-node/backfill/src/test/java/org/hiero/block/node/backfill/BackfillPluginTest.java
  block-node/backfill/src/test/resources/block-nodes-2.json
  block-node/backfill/src/test/resources/block-nodes-3.json
  block-node/backfill/src/test/resources/block-nodes.json
  block-node/messaging/src/main/java/org/hiero/block/node/messaging/BlockMessagingFacilityImpl.java
  block-node/messaging/src/main/java/org/hiero/block/node/messaging/BlockNotificationRingEvent.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockNotificationRingEventTest.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/blockmessaging/BlockMessagingFacility.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/blockmessaging/BlockNotificationHandler.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/blockmessaging/NewestBlockKnownToNetworkNotification.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherHandler.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/StreamPublisherManager.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/fixtures/TestStreamPublisherManager.java
Labels: Feature Enhancement

#1495 test: e2e scenario for On-Demand Happy path flow
  docs/simulator/configuration.md
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializer.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/config/data/BlockStreamConfig.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImpl.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/mode/impl/PublishClientManager.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/logging/SimulatorConfigurationLoggerTest.java
  tools-and-tests/suites/src/main/java/org/hiero/block/suites/BaseSuite.java
  tools-and-tests/suites/src/main/java/org/hiero/block/suites/BlockNodeContainerConfig.java
  tools-and-tests/suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java
  tools-and-tests/suites/src/main/resources/block-nodes.json
Labels: pull request

#1497 feat: Add Support to Stream-Publisher for Handling `EndStream` Messages
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/TestBlockMessagingFacility.java
  block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/BlocksFilesRecentPlugin.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileRecentPluginTest.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherHandler.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/StreamPublisherManager.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManagerTest.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/PublisherHandlerTest.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/fixtures/TestStreamPublisherManager.java
  tools-and-tests/suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java
Labels: pull request

#1519 chore(release): Bump versions for v0.18.0-SNAPSHOT
  charts/block-node-server/Chart.yaml
  charts/blockstream-simulator/Chart.yaml
  version.txt
Labels: Release

#1408 chore: Update CN proto to 0.65.0-rc1
  .github/workflows/pr-checks.yaml
  block-node/protobuf-pbj/src/main/java/module-info.java
  protobuf-sources/build.gradle.kts
  tools-and-tests/protobuf-protoc/src/main/java/module-info.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/generator/CraftBlockStreamManager.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/generator/itemhandler/EventHeaderHandler.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/generator/itemhandler/EventTransactionHandler.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/generator/itemhandler/SignedTransactionHandler.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/itemhandler/EventHeaderHandlerTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/itemhandler/SignedTransactionHandlerTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java
  tools-and-tests/tools/src/main/java/org/hiero/block/tools/commands/BlockInfo.java
  tools-and-tests/tools/src/main/java/org/hiero/block/tools/commands/ConvertToJson.java
Labels: Feature Enhancement, Block Node, Protobuf

#1531 fix(release): fix correct protobuf artifact publish
  .github/workflows/pr-checks.yaml
  .github/workflows/release-push-image.yaml
Labels: Bug

#1544 chore: Remove stack trace from certain debug logs
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherHandler.java
  block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/BlockStreamSubscriberSession.java
Labels: Improvement, Block Node

#1543 fix(1523): Prevent Unexpected OutOfMemoryError under high load
  block-node/app/docker/update-env.sh
  block-node/messaging/src/main/java/org/hiero/block/node/messaging/MessagingConfig.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockMessagingServiceBlockNotificationTest.java
  charts/block-node-server/values-overrides/mid-size.yaml
  charts/block-node-server/values-overrides/mini.yaml
  charts/block-node-server/values.yaml
  docs/block-node/configuration.md
Labels: Block Node

#1546 chore: Add logs to health plugin
  block-node/health/src/main/java/org/hiero/block/node/health/HealthServicePlugin.java
Labels: Improvement

#1547 test(e2e-solo): Initial Version of E2E test using Solo, currently only on-dispatch.
  .github/workflows/solo-e2e-test.yml
Labels: github_actions

#1564 fix: Clear `queueByMap` When Verification Fails
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java
Labels: pull request
