Repository hiero-ledger/hiero-block-node, pull requests merged in 2025-05, with the labels that each got.

#1083 feat: BlockNodeContext Executor Service Factory Method
  block-node/app/build.gradle.kts
  block-node/app/src/main/java/org/hiero/block/node/app/BlockNodeApp.java
  block-node/app/src/main/java/org/hiero/block/node/app/DefaultThreadPoolManager.java
  block-node/app/src/test/java/org/hiero/block/node/app/DefaultThreadPoolManagerTest.java
  block-node/app/src/testFixtures/java/module-info.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/async/TestThreadPoolManager.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/PluginTestBase.java
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPluginTest.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchiveTest.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/TestConfig.java
  block-node/s3-archive/src/main/java/org/hiero/block/node/archive/s3/S3ArchivePlugin.java
  block-node/s3-archive/src/test/java/org/hiero/block/node/archive/s3/S3ArchivePluginTest.java
  block-node/spi/src/main/java/module-info.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/BlockNodeContext.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/threading/ThreadPoolManager.java
Labels: pull request

#1085 chore: Update MAINTAINERS.md
  MAINTAINERS.md
Labels: Documentation

#1076 test: Add subscriber plugin Tests
  block-node/app/build.gradle.kts
  block-node/stream-subscriber/build.gradle.kts
  block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/BlockStreamSubscriberSession.java
  block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java
  block-node/stream-subscriber/src/test/java/org/hiero/block/node/stream/subscriber/BlockStreamSubscriberSessionTest.java
  block-node/stream-subscriber/src/test/java/org/hiero/block/node/stream/subscriber/SubscriberConfigTest.java
  block-node/stream-subscriber/src/test/java/org/hiero/block/node/stream/subscriber/SubscriberTest.java
  suites/src/main/java/org/hiero/block/suites/subscriber/SubscriberTestSuites.java
  suites/src/main/java/org/hiero/block/suites/subscriber/negative/NegativeSingleSubscriberTests.java
  suites/src/main/java/org/hiero/block/suites/subscriber/positive/PositiveMultipleSubscribersTests.java
  suites/src/main/java/org/hiero/block/suites/subscriber/positive/PositiveSingleSubscriberTests.java
Labels: Tests, Subscriber Plugin

#1092 fix: Local Node CI Tests Build Failure
  .github/workflows/local-node-test-reusable.yaml
Labels: pull request

#1098 build(deps): upgrading Java to 21.0.7+6 due to an issue with M4 Apple Silicon.
  block-node/app/docker/Dockerfile
Labels: dependencies

#1100 chore(release): Bump versions for v0.11.0-SNAPSHOT
  charts/block-node-server/Chart.yaml
  charts/blockstream-simulator/Chart.yaml
  version.txt
Labels: Release

#1136 fix: BN is Unable to Restart due to `BlocksFilesHistoric` Plugin
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
Labels: pull request

#1113 docs: Create a logging guidelines document
  docs/logging-guidelines.md
Labels: Block Node

#1140 chore: Cherry pick 1136
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
Labels: Bug

#1133 chore: Finalize the Stream Subscriber plugin
  block-node/app/src/main/java/org/hiero/block/node/app/DefaultThreadPoolManager.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/async/TestThreadPoolManager.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/GrpcPluginTestBase.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/PluginTestBase.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/threading/ThreadPoolManager.java
  block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/BlockStreamSubscriberSession.java
  block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java
  block-node/stream-subscriber/src/test/java/org/hiero/block/node/stream/subscriber/SubscriberTest.java
  block-node/subscriber/build.gradle.kts
  block-node/subscriber/src/main/java/module-info.java
  block-node/subscriber/src/main/java/org/hiero/block/node/subscriber/BlockStreamSubscriberSession.java
  block-node/subscriber/src/main/java/org/hiero/block/node/subscriber/SubscriberServicePlugin.java
  block-node/subscriber/src/test/java/org/hiero/block/node/subscriber/SubscriberTest.java
  settings.gradle.kts
Labels: Block Node

#1147 fix: Adjust block access service to be correct without workarounds
  block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java
  block-node/block-access/src/test/java/org/hiero/block/node/access/service/BlockAccessServicePluginTest.java
  protobuf/src/main/proto/org/hiero/block/api/block_access_service.proto
  suites/src/main/java/org/hiero/block/suites/block/access/GetBlockApiTests.java
  suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java
  suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java
Labels: Bug, Block Node

#872 feat: changed container work dir from app to opt
  block-node/app/docker/Dockerfile
  block-node/app/docker/docker-compose.yml
  block-node/app/docker/logging.properties
  block-node/app/docker/update-env.sh
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/FilesHistoricConfig.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/FilesHistoricConfigTest.java
  block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/FilesRecentConfig.java
  charts/block-node-server/README.md
  charts/block-node-server/templates/deployment.yaml
  charts/block-node-server/templates/pvc-logging.yaml
  charts/block-node-server/values-overrides/mini.yaml
  charts/block-node-server/values.yaml
  simulator/docker/Dockerfile
  simulator/docker/update-env.sh
  simulator/src/main/resources/logging.properties
  suites/src/main/java/org/hiero/block/suites/persistence/positive/PositiveDataPersistenceTests.java
Labels: pull request

#1153 chore: Cherry pick #1147 into `release/0.10` branch for `0.10.0-rc3` and final RC version.
  block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java
  block-node/block-access/src/test/java/org/hiero/block/node/access/service/BlockAccessServicePluginTest.java
  protobuf/src/main/proto/org/hiero/block/api/block_access_service.proto
  suites/src/main/java/org/hiero/block/suites/block/access/GetBlockApiTests.java
  suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java
  suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java
Labels: Improvement, Block Node

#1152 fix: Publisher API is missing some request forms
  block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java
  block-node/publisher/src/main/java/org/hiero/block/node/publisher/PublisherServicePlugin.java
  block-node/publisher/src/test/java/org/hiero/block/node/publisher/PublisherTest.java
  protobuf/src/main/proto/org/hiero/block/api/block_stream_publish_service.proto
  simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamObserver.java
  simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamServerObserver.java
  simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java
  simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamServerObserverTest.java
Labels: Block Node

#1135 chore: Improve block node protobuf devex
  .github/workflows/release-push-image.yaml
  .gitignore
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/blocks/SimpleTestBlockItemBuilder.java
  block-node/s3-archive/src/main/java/org/hiero/block/node/archive/s3/S3ArchivePlugin.java
  block-node/spi/src/test/java/org/hiero/block/node/spi/historicalblocks/BlockAccessorTest.java
  protobuf/build.gradle.kts
  protobuf/scripts/build-bn-proto.sh
  protobuf/src/main/proto/org/hiero/block/api/block_access_service.proto
  protobuf/src/main/proto/org/hiero/block/api/node_service.proto
  protobuf/src/main/proto/org/hiero/block/api/proof_service.proto
  protobuf/src/main/proto/org/hiero/block/api/shared_message_types.proto
  settings.gradle.kts
  simulator/src/main/java/org/hiero/block/simulator/generator/itemhandler/BlockHeaderHandler.java
  simulator/src/test/java/org/hiero/block/simulator/generator/itemhandler/BlockHeaderHandlerTest.java
Labels: Improvement, Block Node

#1170 chore: clean-up of unneeded module block-provider/cloud.historic
  block-node/app/build.gradle.kts
  block-node/block-providers/cloud.historic/build.gradle.kts
  block-node/block-providers/cloud.historic/src/main/java/module-info.java
  block-node/block-providers/cloud.historic/src/main/java/org/hiero/block/node/blocks/cloud/historic/BlocksCloudHistoricPlugin.java
  settings.gradle.kts
Labels: Improvement, Block Node

#1155 fix: Moved GRPC services over to use PBJ generated ones
  block-node/block-access/src/main/java/module-info.java
  block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java
  block-node/block-access/src/test/java/org/hiero/block/node/access/service/BlockAccessServicePluginTest.java
  block-node/publisher/src/main/java/org/hiero/block/node/publisher/PublisherServicePlugin.java
  block-node/publisher/src/test/java/org/hiero/block/node/publisher/PublisherTest.java
  block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java
  block-node/stream-subscriber/src/test/java/org/hiero/block/node/stream/subscriber/SubscriberTest.java
  protobuf/src/main/java/module-info.java
Labels: Block Node

#1137 feat: create server status plugin
  block-node/app/build.gradle.kts
  block-node/server-status/build.gradle.kts
  block-node/server-status/src/main/java/module-info.java
  block-node/server-status/src/main/java/org/hiero/block/node/server/status/ServerStatusServicePlugin.java
  block-node/server-status/src/test/java/org/hiero/block/node/server/status/ServerStatusServicePluginTest.java
  settings.gradle.kts
  suites/src/main/java/org/hiero/block/suites/BaseSuite.java
  suites/src/main/java/org/hiero/block/suites/server/status/ServerStatusTestSuites.java
  suites/src/main/java/org/hiero/block/suites/server/status/positive/PositiveServerStatusTests.java
  suites/src/main/java/org/hiero/block/suites/utils/ServerStatusUtils.java
Labels: New Feature, Server Status Plugin

#1176 fix: BlockStream Image Container broken
  protobuf/src/main/java/module-info.java
  simulator/docker/Dockerfile
Labels: Bug

#1172 chore: Update MAINTAINERS.md to point to the master guidelines
  MAINTAINERS.md
Labels: Documentation

#1120 docs: Add metrics document
  docs/block-node/metrics.md
Labels: Documentation

#1174 chore: Clean up ThreadPoolManager API
  block-node/app/src/main/java/org/hiero/block/node/app/DefaultThreadPoolManager.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/async/TestThreadPoolManager.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/threading/ThreadPoolManager.java
  block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java
Labels: Block Node

#1182 chore(release): Bump versions for v0.12.0-SNAPSHOT
  charts/block-node-server/Chart.yaml
  charts/blockstream-simulator/Chart.yaml
  version.txt
Labels: Release

#1186 fix: Add protobuf path to artificat upload and fail on error
  .github/workflows/release-push-image.yaml
Labels: Release

#1185 fix: (release/0.11) Add protobuf path to artificat upload and fail on error
  .github/workflows/release-push-image.yaml
Labels: Release

#1191 fix: Opening for reflection, so Simulator can run in Consumer mode using modules (Docker or K8s)
  protobuf/src/main/java/module-info.java
Labels: Simulator

#1196 fix: Opening for reflection, so Simulator can run in Consumer mode
  protobuf/src/main/java/module-info.java
Labels: Bug, Simulator

#1214 chore: Renamed two misnamed response code enumerations.
  protobuf/src/main/proto/org/hiero/block/api/block_stream_publish_service.proto
Labels: Publisher Plugin, Protobuf

#1175 docs: Update the publisher protocol document to include the multi-publisher extension
  docs/assets/Multi-Publisher-Diagram.svg
  docs/design/communication-protocol/publish-block-stream.md
Labels: Documentation
