Repository hiero-ledger/hiero-block-node, pull requests merged in 2025-03, with the labels that each got.

#745 fix: Improvements and fixes to Helm charts and docker compose
  charts/block-node-server/values.yaml
  charts/blockstream-simulator/templates/deployment.yaml
  charts/blockstream-simulator/values-overrides/consumer.yaml
  charts/blockstream-simulator/values.yaml
  simulator/docker/update-env.sh
Labels: Improvement, Block Node

#761 build(deps): Upgrade Swirlds dependency to `0.59.2`
  hiero-dependency-versions/build.gradle.kts
  server/src/test/java/com/hedera/block/server/config/TestConfigBuilder.java
  server/src/test/java/com/hedera/block/server/config/logging/ConfigurationLoggingImplTest.java
  server/src/test/java/com/hedera/block/server/persistence/StreamPersistenceHandlerImplTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/archive/LocalGroupZipArchiveTaskTest.java
  server/src/test/java/com/hedera/block/server/util/TestConfigUtil.java
  simulator/src/test/java/com/hedera/block/simulator/TestUtils.java
  simulator/src/test/java/com/hedera/block/simulator/config/TestConfigBuilder.java
Labels: dependencies

#691 chore: Document some thoughts for nano-service approach
  docs/design/Nano-Service-Approach.md
  docs/design/assets/Block-Node-Nano-Services.svg
Labels: pull request

#770 ci: Update ubuntu runners to 24.04 and 22.04
  .github/workflows/zxc-verify-gradle-build-determinism.yaml
Labels: github_actions

#760 feat: open-range historic to live streaming
  charts/block-node-server/dashboards/block-node-server.json
  server/docker/logging.properties
  server/docker/metrics/dashboards/block-node-server.json
  server/docs/design/historic-streaming/open-range-historic-streaming.md
  server/src/main/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializer.java
  server/src/main/java/com/hedera/block/server/consumer/AsyncConsumerStreamResponseObserver.java
  server/src/main/java/com/hedera/block/server/consumer/ConsumerConfig.java
  server/src/main/java/com/hedera/block/server/consumer/ConsumerStreamBuilder.java
  server/src/main/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserver.java
  server/src/main/java/com/hedera/block/server/consumer/ConsumerStreamRunnable.java
  server/src/main/java/com/hedera/block/server/consumer/Functions.java
  server/src/main/java/com/hedera/block/server/consumer/HistoricBlockStreamSupplier.java
  server/src/main/java/com/hedera/block/server/consumer/HistoricDataPoller.java
  server/src/main/java/com/hedera/block/server/consumer/HistoricDataPollerImpl.java
  server/src/main/java/com/hedera/block/server/consumer/LiveStreamEventHandlerBuilder.java
  server/src/main/java/com/hedera/block/server/consumer/OpenRangeStreamManager.java
  server/src/main/java/com/hedera/block/server/consumer/StreamManager.java
  server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorImpl.java
  server/src/main/java/com/hedera/block/server/mediator/LiveStreamPoller.java
  server/src/main/java/com/hedera/block/server/mediator/MediatorConfig.java
  server/src/main/java/com/hedera/block/server/mediator/NoOpLiveStreamMediator.java
  server/src/main/java/com/hedera/block/server/mediator/Poller.java
  server/src/main/java/com/hedera/block/server/mediator/SubscriptionHandler.java
  server/src/main/java/com/hedera/block/server/mediator/SubscriptionHandlerBase.java
  server/src/main/java/com/hedera/block/server/metrics/BlockNodeMetricTypes.java
  server/src/main/java/com/hedera/block/server/notifier/NotifierConfig.java
  server/src/main/java/com/hedera/block/server/notifier/NotifierImpl.java
  server/src/main/java/com/hedera/block/server/pbj/PbjBlockStreamServiceProxy.java
  server/src/main/java/com/hedera/block/server/verification/StreamVerificationHandlerImpl.java
  server/src/main/java/com/hedera/block/server/verification/session/BlockVerificationSessionBase.java
  server/src/main/resources/app.properties
  server/src/main/resources/helidon.properties
  server/src/test/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializerTest.java
  server/src/test/java/com/hedera/block/server/config/logging/ConfigurationLoggingImplTest.java
  server/src/test/java/com/hedera/block/server/consumer/ConsumerConfigTest.java
  server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java
  server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamRunnableTest.java
  server/src/test/java/com/hedera/block/server/consumer/OpenRangeStreamManagerTest.java
  server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
  server/src/test/java/com/hedera/block/server/mediator/MediatorConfigTest.java
  server/src/test/java/com/hedera/block/server/notifier/NotifierConfigTest.java
  server/src/test/java/com/hedera/block/server/notifier/NotifierImplTest.java
  server/src/test/java/com/hedera/block/server/pbj/PbjBlockStreamServiceIntegrationTest.java
  server/src/test/resources/batch-consumers.sh
  server/src/test/resources/smoke-test.sh
  simulator/src/main/resources/app.properties
Labels: New Feature, Block Node

#786 chore: remove sleep on completeStreaming() in Simulator
  simulator/src/main/java/com/hedera/block/simulator/grpc/impl/PublishStreamGrpcClientImpl.java
  simulator/src/test/java/com/hedera/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java
Labels: Simulator

#788 chore: Update issue templates
  .github/ISSUE_TEMPLATE/01-Story-Template.yml
  .github/ISSUE_TEMPLATE/02-Epic-Template.yml
  .github/ISSUE_TEMPLATE/03-Bug-Template.yml
Labels: pull request

#784 chore: removal of the BlockNodeContext object
  server/src/main/java/com/hedera/block/server/BlockNodeAppInjectionModule.java
  server/src/main/java/com/hedera/block/server/config/BlockNodeContext.java
  server/src/main/java/com/hedera/block/server/config/ConfigInjectionModule.java
  server/src/main/java/com/hedera/block/server/consumer/ClosedRangeHistoricStreamEventHandlerBuilder.java
  server/src/main/java/com/hedera/block/server/consumer/ConsumerStreamBuilder.java
  server/src/main/java/com/hedera/block/server/consumer/HistoricBlockStreamSupplier.java
  server/src/main/java/com/hedera/block/server/consumer/HistoricDataPollerImpl.java
  server/src/main/java/com/hedera/block/server/consumer/OpenRangeStreamManager.java
  server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorBuilder.java
  server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorImpl.java
  server/src/main/java/com/hedera/block/server/mediator/LiveStreamPoller.java
  server/src/main/java/com/hedera/block/server/mediator/MediatorInjectionModule.java
  server/src/main/java/com/hedera/block/server/mediator/NoOpLiveStreamMediator.java
  server/src/main/java/com/hedera/block/server/mediator/SubscriptionHandlerBase.java
  server/src/main/java/com/hedera/block/server/notifier/NotifierImpl.java
  server/src/main/java/com/hedera/block/server/pbj/PbjBlockAccessServiceProxy.java
  server/src/main/java/com/hedera/block/server/pbj/PbjBlockStreamServiceProxy.java
  server/src/main/java/com/hedera/block/server/persistence/PersistenceInjectionModule.java
  server/src/main/java/com/hedera/block/server/persistence/StreamPersistenceHandlerImpl.java
  server/src/main/java/com/hedera/block/server/producer/NoOpProducerObserver.java
  server/src/main/java/com/hedera/block/server/producer/ProducerBlockItemObserver.java
  server/src/main/java/com/hedera/block/server/service/ServiceStatusImpl.java
  server/src/test/java/com/hedera/block/server/BlockNodeAppInjectionModuleTest.java
  server/src/test/java/com/hedera/block/server/BlockNodeAppTest.java
  server/src/test/java/com/hedera/block/server/config/BlockNodeContextTest.java
  server/src/test/java/com/hedera/block/server/config/ConfigInjectionModuleTest.java
  server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java
  server/src/test/java/com/hedera/block/server/consumer/HistoricBlockStreamSupplierTest.java
  server/src/test/java/com/hedera/block/server/consumer/OpenRangeStreamManagerTest.java
  server/src/test/java/com/hedera/block/server/grpc/BlockAccessServiceTest.java
  server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
  server/src/test/java/com/hedera/block/server/mediator/MediatorInjectionModuleTest.java
  server/src/test/java/com/hedera/block/server/metrics/MetricsInjectionModuleTest.java
  server/src/test/java/com/hedera/block/server/metrics/MetricsServiceTest.java
  server/src/test/java/com/hedera/block/server/notifier/NotifierImplTest.java
  server/src/test/java/com/hedera/block/server/pbj/PbjBlockAccessServiceProxyTest.java
  server/src/test/java/com/hedera/block/server/pbj/PbjBlockStreamServiceIntegrationTest.java
  server/src/test/java/com/hedera/block/server/persistence/PersistenceInjectionModuleTest.java
  server/src/test/java/com/hedera/block/server/persistence/StreamPersistenceHandlerImplTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/compression/ZstdCompressionTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/path/BlockAsLocalFilePathResolverTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/remove/BlockAsLocalFileRemoverTest.java
  server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java
  server/src/test/java/com/hedera/block/server/util/TestConfigUtil.java
Labels: Block Node

#722 feat: allow for configuration of the async writers executors
  server/docs/configuration.md
  server/src/main/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializer.java
  server/src/main/java/com/hedera/block/server/persistence/PersistenceInjectionModule.java
  server/src/main/java/com/hedera/block/server/persistence/storage/PersistenceStorageConfig.java
  server/src/main/java/com/hedera/block/server/persistence/storage/write/AsyncWriterExecutorFactory.java
  server/src/test/java/com/hedera/block/server/config/ServerMappedConfigSourceInitializerTest.java
  server/src/test/java/com/hedera/block/server/config/logging/ConfigurationLoggingImplTest.java
  server/src/test/java/com/hedera/block/server/manager/AckHandlerInjectionModuleTest.java
  server/src/test/java/com/hedera/block/server/persistence/PersistenceInjectionModuleTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/PersistenceStorageConfigTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/write/AsyncWriterExecutorFactoryTest.java
Labels: Block Node

#795 feat: BN server Helm various improvements
  charts/block-node-server/templates/NOTES.txt
  charts/block-node-server/templates/_helpers.tpl
  charts/block-node-server/templates/configmap-logging.yaml
  charts/block-node-server/templates/configmap.yaml
  charts/block-node-server/templates/deployment.yaml
  charts/block-node-server/templates/grafana-datasource.yaml
  charts/block-node-server/templates/ingress.yaml
  charts/block-node-server/templates/pvc-archive.yaml
  charts/block-node-server/templates/pvc-live.yaml
  charts/block-node-server/templates/secret.yaml
  charts/block-node-server/templates/service.yaml
  charts/block-node-server/templates/serviceaccount.yaml
  charts/block-node-server/templates/servicemonitor.yaml
  charts/block-node-server/values-overrides/mini.yaml
  charts/block-node-server/values.yaml
Labels: Release, Block Node

#797 chore: fixed disabled tests
  server/src/main/java/com/hedera/block/server/consumer/OpenRangeStreamManager.java
  server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorBuilder.java
  server/src/main/java/com/hedera/block/server/mediator/LiveStreamMediatorImpl.java
  server/src/main/java/com/hedera/block/server/mediator/SubscriptionHandlerBase.java
  server/src/main/java/com/hedera/block/server/notifier/NotifierImpl.java
  server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamResponseObserverTest.java
  server/src/test/java/com/hedera/block/server/consumer/ConsumerStreamRunnableTest.java
  server/src/test/java/com/hedera/block/server/consumer/OpenRangeStreamManagerTest.java
  server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
  server/src/test/java/com/hedera/block/server/notifier/NotifierImplTest.java
  server/src/test/java/com/hedera/block/server/pbj/PbjBlockStreamServiceIntegrationTest.java
  server/src/test/java/com/hedera/block/server/util/PbjProtoTestUtils.java
Labels: Tests

#802 feat: Simple Persistence startup data
  server/src/main/java/com/hedera/block/server/ack/AckHandlerImpl.java
  server/src/main/java/com/hedera/block/server/persistence/StreamPersistenceHandlerImpl.java
  server/src/main/java/com/hedera/block/server/persistence/storage/archive/LocalGroupZipArchiveTask.java
  server/src/main/java/com/hedera/block/server/persistence/storage/path/BlockAsLocalFilePathResolver.java
  server/src/main/java/com/hedera/block/server/persistence/storage/path/BlockPathResolver.java
  server/src/main/java/com/hedera/block/server/persistence/storage/path/NoOpBlockPathResolver.java
  server/src/main/java/com/hedera/block/server/service/ServiceStatus.java
  server/src/main/java/com/hedera/block/server/service/ServiceStatusImpl.java
  server/src/test/java/com/hedera/block/server/ack/AckHandlerImplTest.java
  server/src/test/java/com/hedera/block/server/ack/AckHandlerInjectionModuleTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/path/BlockAsLocalFilePathResolverTest.java
  server/src/test/java/com/hedera/block/server/persistence/storage/path/NoOpBlockPathResolverTest.java
  simulator/src/main/java/com/hedera/block/simulator/config/data/BlockGeneratorConfig.java
  simulator/src/main/resources/app.properties
Labels: pull request

#804 chore(release): Bump versions for v0.7.0-SNAPSHOT
  charts/block-node-server/Chart.yaml
  charts/blockstream-simulator/Chart.yaml
  version.txt
Labels: Release

#820 chore: Set on pull_request_target for PR formatting check GHA
  .github/workflows/pr-formatting.yaml
Labels: github_actions

#766 chore: improvements for test repeatability
  server/src/main/java/com/hedera/block/server/pbj/PbjBlockStreamServiceProxy.java
  server/src/test/java/com/hedera/block/server/mediator/LiveStreamMediatorImplTest.java
  server/src/test/java/com/hedera/block/server/pbj/PbjBlockStreamServiceIntegrationTest.java
  server/src/test/java/com/hedera/block/server/util/BlockingExecutorService.java
  server/src/test/java/com/hedera/block/server/util/TestUtils.java
Labels: Block Node, pull request

#817 fix: Various Bugs found on `0.6.0-rc1` deployment.
  charts/block-node-server/templates/deployment.yaml
  server/src/main/java/org/hiero/block/server/producer/ProducerBlockItemObserver.java
  server/src/test/java/org/hiero/block/server/producer/ProducerBlockItemObserverTest.java
Labels: Bug

#834 ci: Fix triggers for e2e-tests, smoke-test, and pr-checks
  .github/workflows/e2e-tests.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/smoke-test.yaml
Labels: github_actions

#823 fix: Various Bugs found on `0.6.0-rc1` deployment. (Cherry-pick of #817 into `release/0.6` branch)
  .github/workflows/e2e-tests.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/smoke-test.yaml
  charts/block-node-server/templates/deployment.yaml
  server/src/main/java/com/hedera/block/server/producer/ProducerBlockItemObserver.java
  server/src/test/java/com/hedera/block/server/producer/ProducerBlockItemObserverTest.java
Labels: Bug, Block Node

#841 chore: follow-up for hiero package move
  block-node/base/build.gradle.kts
  block-node/base/src/main/java/module-info.java
  block-node/server/src/main/java/module-info.java
  common/src/main/java/module-info.java
  settings.gradle.kts
  simulator/src/main/java/module-info.java
  stream/build.gradle.kts
  stream/src/main/java/module-info.java
  tools/build.gradle.kts
Labels: pull request

#849 feat: Configured Observability stack to use PVC on Helm Charts
  charts/block-node-server/templates/deployment.yaml
  charts/block-node-server/values-overrides/mini.yaml
  charts/block-node-server/values.yaml
Labels: Block Node

#848 chore: Add "facilities" wording to nano-service document.
  docs/design/Nano-Service-Approach.md
  docs/design/assets/Block-Node-Nano-Services.svg
Labels: pull request

#875 fix: restart recovery race condition
  block-node/base/src/main/java/org/hiero/block/server/ack/AckHandlerImpl.java
  block-node/base/src/test/java/org/hiero/block/server/ack/AckHandlerImplTest.java
Labels: Bug, Block Node

#859 feat: Add messaging module
  block-node/messaging/build.gradle.kts
  block-node/messaging/src/main/java/module-info.java
  block-node/messaging/src/main/java/org/hiero/block/server/messaging/BlockItemHandler.java
  block-node/messaging/src/main/java/org/hiero/block/server/messaging/BlockNotification.java
  block-node/messaging/src/main/java/org/hiero/block/server/messaging/BlockNotificationHandler.java
  block-node/messaging/src/main/java/org/hiero/block/server/messaging/MessagingService.java
  block-node/messaging/src/main/java/org/hiero/block/server/messaging/NoBackPressureBlockItemHandler.java
  block-node/messaging/src/main/java/org/hiero/block/server/messaging/impl/BlockItemBatchRingEvent.java
  block-node/messaging/src/main/java/org/hiero/block/server/messaging/impl/BlockNotificationRingEvent.java
  block-node/messaging/src/main/java/org/hiero/block/server/messaging/impl/MessagingConfig.java
  block-node/messaging/src/main/java/org/hiero/block/server/messaging/impl/MessagingServiceImpl.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockItemBatchRingEventTest.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockNotificationRingEventTest.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/MessagingServiceBlockItemTest.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/MessagingServiceBlockNotificationTest.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/MessagingServiceDynamicBlockItemTest.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/MessagingServiceExceptionTest.java
  settings.gradle.kts
Labels: pull request

#855 chore: Resolve and Enable E2E tests
  suites/src/main/java/module-info.java
  suites/src/main/java/org/hiero/block/suites/BaseSuite.java
  suites/src/main/java/org/hiero/block/suites/grpc/positive/PositiveEndpointBehaviourTests.java
  suites/src/main/java/org/hiero/block/suites/persistence/positive/PositiveDataPersistenceTests.java
Labels: Tests

#876 chore: Cherry pick 875 into `release/0.6` branch
  server/src/main/java/com/hedera/block/server/ack/AckHandlerImpl.java
  server/src/test/java/com/hedera/block/server/ack/AckHandlerImplTest.java
Labels: Bug

#821 chore: named injection for components with a common interface
  block-node/base/src/main/java/module-info.java
  block-node/base/src/main/java/org/hiero/block/server/persistence/PersistenceInjectionModule.java
  block-node/base/src/main/java/org/hiero/block/server/utils/InjectionConstants.java
  block-node/base/src/main/java/org/hiero/block/server/verification/StreamVerificationHandlerImpl.java
  block-node/base/src/main/java/org/hiero/block/server/verification/VerificationInjectionModule.java
  block-node/server/src/main/java/org/hiero/block/server/pbj/PbjBlockStreamServiceProxy.java
Labels: pull request

#871 chore: Remove unneeded dependency on slf4j
  block-node/base/build.gradle.kts
  block-node/messaging/build.gradle.kts
  block-node/server/build.gradle.kts
  common/src/main/java/module-info.java
  common/src/main/java/org/hiero/block/common/hasher/HashingUtilities.java
  common/src/main/java/org/hiero/block/common/hasher/StreamingTreeHasher.java
  simulator/build.gradle.kts
  tools/build.gradle.kts
Labels: pull request

#873 docs: Block content proof design
  block-node/server/docs/design/block-content-proof.md
Labels: Design, Block Node

#827 feat: Centralize Record Configuration Logging for Simulator
  simulator/docker/Dockerfile
  simulator/docker/update-env.sh
  simulator/src/main/java/org/hiero/block/simulator/BlockStreamSimulatorApp.java
  simulator/src/main/java/org/hiero/block/simulator/config/ConfigInjectionModule.java
  simulator/src/main/java/org/hiero/block/simulator/config/data/BlockGeneratorConfig.java
  simulator/src/main/java/org/hiero/block/simulator/config/data/BlockStreamConfig.java
  simulator/src/main/java/org/hiero/block/simulator/config/data/ConsumerConfig.java
  simulator/src/main/java/org/hiero/block/simulator/config/data/GrpcConfig.java
  simulator/src/main/java/org/hiero/block/simulator/config/logging/ConfigurationLogging.java
  simulator/src/main/java/org/hiero/block/simulator/config/logging/Loggable.java
  simulator/src/main/java/org/hiero/block/simulator/config/logging/SimulatorConfigurationLogger.java
  simulator/src/main/resources/logging.properties
  simulator/src/test/java/org/hiero/block/simulator/BlockStreamSimulatorTest.java
  simulator/src/test/java/org/hiero/block/simulator/StackTracesTest.java
  simulator/src/test/java/org/hiero/block/simulator/config/ConfigInjectionModuleTest.java
  simulator/src/test/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java
  simulator/src/test/java/org/hiero/block/simulator/config/logging/SimulatorConfigurationLoggerTest.java
  simulator/src/test/java/org/hiero/block/simulator/config/logging/TestSecretConfig.java
Labels: pull request

#887 chore: Remove docker determinism checks for now.
  .github/workflows/pr-checks.yaml
  .github/workflows/release-push-image.yaml
  .github/workflows/support/scripts/generate-docker-artifact-baseline.sh
  .github/workflows/zxc-verify-docker-build-determinism.yaml
Labels: github_actions

#905 chore: Adjust workflows to reduce "stuck" jobs via reduced priority and time limits.
  .github/workflows/e2e-tests.yaml
  .github/workflows/helm-charts.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/pr-formatting.yaml
  .github/workflows/release-automation.yaml
  .github/workflows/release-push-image.yaml
  .github/workflows/smoke-test.yaml
  .github/workflows/zxc-verify-gradle-build-determinism.yaml
Labels: CI/CD

#910 chore: fix gradle build to use module path
  block-node/app/build.gradle.kts
Labels: Block Node

#885 chore: Add a document explaining block node types and tiers
  docs/Block-Node-Types.md
  docs/assets/Block-Node-Tiers-and-Types.svg
Labels: Documentation

#900 feat: Simple Simulator Startup Data
  charts/blockstream-simulator/templates/deployment.yaml
  charts/blockstream-simulator/templates/pvc-simulator-data.yaml
  charts/blockstream-simulator/values.yaml
  simulator/build.gradle.kts
  simulator/docker/Dockerfile
  simulator/docker/docker-compose-publisher-consumer.yml
  simulator/docker/docker-compose-publisher.yml
  simulator/docker/update-env.sh
  simulator/src/main/java/org/hiero/block/simulator/BlockStreamSimulatorInjectionComponent.java
  simulator/src/main/java/org/hiero/block/simulator/config/ConfigInjectionModule.java
  simulator/src/main/java/org/hiero/block/simulator/config/SimulatorConfigExtension.java
  simulator/src/main/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializer.java
  simulator/src/main/java/org/hiero/block/simulator/config/data/SimulatorStartupDataConfig.java
  simulator/src/main/java/org/hiero/block/simulator/generator/CraftBlockStreamManager.java
  simulator/src/main/java/org/hiero/block/simulator/generator/GeneratorInjectionModule.java
  simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImpl.java
  simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamObserver.java
  simulator/src/main/java/org/hiero/block/simulator/startup/SimulatorStartupData.java
  simulator/src/main/java/org/hiero/block/simulator/startup/StartupDataInjectionModule.java
  simulator/src/main/java/org/hiero/block/simulator/startup/impl/SimulatorStartupDataImpl.java
  simulator/src/main/resources/app.properties
  simulator/src/test/java/org/hiero/block/simulator/config/ConfigInjectionModuleTest.java
  simulator/src/test/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java
  simulator/src/test/java/org/hiero/block/simulator/config/logging/SimulatorConfigurationLoggerTest.java
  simulator/src/test/java/org/hiero/block/simulator/generator/CraftBlockStreamManagerTest.java
  simulator/src/test/java/org/hiero/block/simulator/generator/GeneratorInjectionModuleTest.java
  simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java
  simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamObserverTest.java
  simulator/src/test/java/org/hiero/block/simulator/startup/impl/SimulatorStartupDataImplTest.java
Labels: pull request

#916 chore(release): Bump versions for v0.8.0-SNAPSHOT
  charts/block-node-server/Chart.yaml
  charts/blockstream-simulator/Chart.yaml
  version.txt
Labels: Release

#886 docs: Centralizes docs in repo and suggests grouping structure
  .markdownlint.yaml
  README.md
  SECURITY.md
  charts/block-node-server/README.md
  charts/blockstream-simulator/README.md
  docs/Protocol/README.md
  docs/assets/00036-consumer-registration.png
  docs/assets/00036-demo-disruptor-class-diagram.png
  docs/assets/00036-producer-registration.png
  docs/assets/00036-refactor-demo-disruptor.png
  docs/assets/Block-Node-Nano-Services.svg
  docs/configuration.md
  docs/contributing
  docs/design/apis/server-status-api.md
  docs/design/architecture/Nano-Service-Approach.md
  docs/design/block-verification.md
  docs/design/communication-protocol/README.md
  docs/design/communication-protocol/publish-block-stream.md
  docs/design/design-doc-template.md
  docs/design/how-to-design-doc.md
  docs/design/persistence/Addenda/BlockPersistenceTaskBasedWriter.md
  docs/design/persistence/block-persistence.md
  docs/design/proofs/block-content-proof.md
  docs/design/streaming/bidi-producer-consumers-streaming.md
  docs/design/streaming/closed-range-historic-streaming.md
  docs/design/streaming/open-range-historic-streaming.md
  docs/metrics.md
  docs/overview.md
  docs/release.md
  docs/server/README.md
  docs/server/configuration.md
  docs/server/quickstart.md
  docs/simulator/README.md
  docs/simulator/configuration.md
  docs/simulator/quickstart.md
  docs/test-plan/template.md
  docs/tools/README.md
  docs/tools/quickstart.md
  simulator/docs/configuration.md
Labels: Documentation
