Repository hiero-ledger/hiero-block-node, pull requests merged in 2025-09, with the labels that each got.

#1570 fix(verification): Update CN Proto to latest GA Tag and Fix unparsed.proto file
  block-node/verification/src/main/java/org/hiero/block/node/verification/BlockVerificationSession.java
  common/src/main/java/org/hiero/block/common/hasher/HashingUtilities.java
  protobuf-sources/build.gradle.kts
  protobuf-sources/src/main/proto/internal/unparsed.proto
Labels: Bug

#1568 chore(1542): Add sudo and keep container active
  block-node/app/docker/Dockerfile
Labels: Block Node, Performance

#1572 fix(patch): Cherry picks for 0.17.1
  block-node/app/docker/Dockerfile
  block-node/app/docker/update-env.sh
  block-node/health/src/main/java/org/hiero/block/node/health/HealthServicePlugin.java
  block-node/messaging/src/main/java/org/hiero/block/node/messaging/MessagingConfig.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockMessagingServiceBlockNotificationTest.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherHandler.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/StreamPublisherPluginTest.java
  block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/BlockStreamSubscriberSession.java
  block-node/verification/src/main/java/org/hiero/block/node/verification/BlockVerificationSession.java
  charts/block-node-server/values-overrides/mid-size.yaml
  charts/block-node-server/values-overrides/mini.yaml
  charts/block-node-server/values.yaml
  common/src/main/java/org/hiero/block/common/hasher/HashingUtilities.java
  docs/block-node/configuration.md
  protobuf-sources/build.gradle.kts
  protobuf-sources/src/main/proto/internal/unparsed.proto
Labels: Release

#1566 test: Multi-Publisher Plugin E2E Test Plan
  docs/test-plan/publisher/stream-publisher-e2e-test-plan.md
Labels: pull request

#1548 test(e2e-solo): Follow-up to GHA E2E Solo Test
  .github/workflows/solo-e2e-test.yml
Labels: github_actions, Tests

#1410 chore: Create basic config file .gitvote.yml
  .gitvote.yml
Labels: Improvement, Block Node

#1594 chore(release): Bump versions for v0.19.0-SNAPSHOT
  charts/block-node-server/Chart.yaml
  charts/blockstream-simulator/Chart.yaml
  version.txt
Labels: Release

#1632 feat: Change telemetry defaults to false
  charts/block-node-server/values-overrides/nano.yaml
  charts/block-node-server/values.yaml
Labels: Helm - Deploy

#1590 fix(1522): Remove NPE opportunities and runtime exceptions from block accessors
  block-node/app-config/src/main/java/module-info.java
  block-node/app/build.gradle.kts
  block-node/app/src/main/resources/logging.properties
  block-node/app/src/testFixtures/java/module-info.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/TestUtils.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/blocks/InMemoryBlockAccessor.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/blocks/MinimalBlockAccessor.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/blocks/SimpleTestBlockItemBuilder.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/SimpleInMemoryHistoricalBlockFacility.java
  block-node/backfill/src/main/java/org/hiero/block/node/backfill/BackfillPlugin.java
  block-node/backfill/src/test/java/org/hiero/block/node/backfill/BackfillPluginTest.java
  block-node/base/src/test/java/org/hiero/block/node/base/tar/TaredBlockIteratorTest.java
  block-node/block-providers/files.historic/src/main/java/module-info.java
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlockFileHistoricPlugin.java
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/ZipBlockAccessor.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlockFileHistoricPluginTest.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockAccessorTest.java
  block-node/block-providers/files.recent/src/main/java/module-info.java
  block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/BlockFileBlockAccessor.java
  block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/BlockFileRecentPlugin.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileBlockAccessorTest.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileRecentPluginTest.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockItemTest.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockNotificationRingEventTest.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockNotificationTest.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/DynamicBlockItemTest.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/FacilityExceptionTest.java
  block-node/s3-archive/src/main/java/org/hiero/block/node/archive/s3/S3ArchivePlugin.java
  block-node/spi/build.gradle.kts
  block-node/spi/src/main/java/module-info.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/blockmessaging/PersistedNotification.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/historicalblocks/BlockAccessor.java
  block-node/spi/src/test/java/org/hiero/block/node/spi/historicalblocks/BlockAccessorTest.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManagerTest.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/PublisherHandlerTest.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/fixtures/TestStreamPublisherManager.java
  tools-and-tests/suites/src/main/java/org/hiero/block/suites/subscriber/negative/NegativeSingleSubscriberTests.java
Labels: Block Provider

#1643 ci(publish): Cherry pick 1641
  .github/workflows/release-push-image.yaml
  build.gradle.kts
  charts/block-node-server/README.md
  charts/blockstream-simulator/README.md
Labels: Bug, Release

#1677 build: bump Gradle plugins to 0.5.1
  settings.gradle.kts
Labels: P1
