Repository hiero-ledger/hiero-block-node, pull requests merged in 2025-07, with the labels that each got.

#1331 chore: Storage Retention Policy E2E Testing
  docs/test-plan/persistence/files-historic-persistence-e2e-test-plan.md
  docs/test-plan/persistence/files-historic-persistence-retention-policy-e2e-test-plan.md
  docs/test-plan/persistence/files-recent-persistence-retention-policy-e2e-test-plan.md
Labels: Block Node, Documentation, pull request

#1366 refactor: Remove Cyclic Module Relationship from Block Node App Module
  block-node/app-config/build.gradle.kts
  block-node/app-config/src/main/java/module-info.java
  block-node/app-config/src/main/java/org/hiero/block/node/app/config/AutomaticEnvironmentVariableConfigSource.java
  block-node/app-config/src/main/java/org/hiero/block/node/app/config/ServerConfig.java
  block-node/app-config/src/main/resources/app.properties
  block-node/app-config/src/test/java/org/hiero/block/node/app/config/AutomaticEnvironmentVariableConfigSourceTest.java
  block-node/app-config/src/test/java/org/hiero/block/node/app/config/TestSecretConfig.java
  block-node/app-config/src/test/resources/app-test.properties
  block-node/app/src/main/java/module-info.java
  block-node/app/src/main/java/org/hiero/block/node/app/BlockNodeApp.java
  block-node/app/src/main/java/org/hiero/block/node/app/logging/ConfigLogger.java
  block-node/app/src/test/java/org/hiero/block/node/app/logging/ConfigLoggerImplTest.java
  block-node/app/src/test/java/org/hiero/block/node/app/logging/TestSecretConfig.java
  block-node/block-providers/files.recent/build.gradle.kts
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileRecentPluginTest.java
  settings.gradle.kts
  tools-and-tests/suites/src/main/java/org/hiero/block/suites/metrics/MetricsCommonTests.java
Labels: pull request

#1365 feat: Files Historic Plugin Retention Policy Granularity Update
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/FilesHistoricConfig.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPluginTest.java
  docs/design/persistence/block-node-retention-policy.md
Labels: pull request

#1363 chore(release): Bump versions for v0.15.0-SNAPSHOT
  charts/block-node-server/Chart.yaml
  charts/blockstream-simulator/Chart.yaml
  version.txt
Labels: Release, Block Node

#1379 chore: Update release 0 14
  block-node/app-config/build.gradle.kts
  block-node/app-config/src/main/java/module-info.java
  block-node/app-config/src/main/java/org/hiero/block/node/app/config/AutomaticEnvironmentVariableConfigSource.java
  block-node/app-config/src/main/java/org/hiero/block/node/app/config/ServerConfig.java
  block-node/app-config/src/main/resources/app.properties
  block-node/app-config/src/test/java/org/hiero/block/node/app/config/AutomaticEnvironmentVariableConfigSourceTest.java
  block-node/app-config/src/test/java/org/hiero/block/node/app/config/TestSecretConfig.java
  block-node/app-config/src/test/resources/app-test.properties
  block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/block-provider-files-historic.json
  block-node/app/docker/metrics/dashboards/Hiero-Block-Node-Plugins/block-provider-files-recent.json
  block-node/app/docker/metrics/dashboards/block-node-server-logs.json
  block-node/app/docker/metrics/prometheus.yml
  block-node/app/src/main/java/module-info.java
  block-node/app/src/main/java/org/hiero/block/node/app/BlockNodeApp.java
  block-node/app/src/main/java/org/hiero/block/node/app/logging/ConfigLogger.java
  block-node/app/src/test/java/org/hiero/block/node/app/logging/ConfigLoggerImplTest.java
  block-node/app/src/test/java/org/hiero/block/node/app/logging/TestSecretConfig.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/TestBlockMessagingFacility.java
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/FilesHistoricConfig.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlockPathTest.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPluginTest.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/FilesHistoricConfigTest.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockAccessorTest.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchiveTest.java
  block-node/block-providers/files.recent/build.gradle.kts
  block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/BlocksFilesRecentPlugin.java
  block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/FilesRecentConfig.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileRecentPluginTest.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/FilesRecentConfigTest.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/BlockNodeContext.java
  charts/block-node-server/dashboards/Hiero-Block-Node-Plugins/block-provider-files-historic.json
  charts/block-node-server/dashboards/Hiero-Block-Node-Plugins/block-provider-files-recent.json
  docs/block-node/metrics.md
  docs/design/persistence/block-node-retention-policy.md
  docs/simulator/quickstart.md
  docs/test-plan/persistence/files-historic-persistence-e2e-test-plan.md
  docs/test-plan/persistence/files-historic-persistence-retention-policy-e2e-test-plan.md
  docs/test-plan/persistence/files-recent-persistence-retention-policy-e2e-test-plan.md
  protobuf-sources/build.gradle.kts
  protobuf-sources/scripts/build-bn-proto.sh
  settings.gradle.kts
  tools-and-tests/simulator/docker/dashboards/block-stream-simulator-consumer.json
  tools-and-tests/simulator/docker/dashboards/block-stream-simulator-publisher.json
  tools-and-tests/simulator/docker/dashboards/provisioner.yaml
  tools-and-tests/simulator/docker/datasources.yml
  tools-and-tests/simulator/docker/docker-compose-publisher-consumer.yml
  tools-and-tests/simulator/docker/docker-compose-publisher.yml
  tools-and-tests/simulator/docker/loki-config.yaml
  tools-and-tests/simulator/docker/simulator-prometheus.yml
  tools-and-tests/simulator/docker/simulator-promtail-config.yaml
  tools-and-tests/simulator/docker/update-env.sh
  tools-and-tests/simulator/src/main/java/module-info.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/logging/CleanColorfulFormatter.java
  tools-and-tests/simulator/src/main/resources/logging.properties
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/StackTracesTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/logging/CleanColorfulFormatterTest.java
  tools-and-tests/suites/src/main/java/org/hiero/block/suites/metrics/MetricsCommonTests.java
Labels: Block Node

#1375 refactor(verification): Hash Refactor to support latest changes on Block Root Hash Algorithm
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/blocks/BlockUtils.java
  block-node/app/src/testFixtures/resources/test-blocks/000000000000000000000000000000000014.blk.gz
  block-node/verification/src/main/java/org/hiero/block/node/verification/BlockVerificationSession.java
  block-node/verification/src/test/java/org/hiero/block/node/verification/BlockVerificationSessionTest.java
  block-node/verification/src/test/java/org/hiero/block/node/verification/VerificationServicePluginTest.java
  common/src/main/java/org/hiero/block/common/hasher/Hashes.java
  common/src/main/java/org/hiero/block/common/hasher/HashingUtilities.java
  protobuf-sources/src/main/proto/internal/unparsed.proto
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/generator/CraftBlockStreamManager.java
Labels: Improvement, Block Node

#1383 chore: TAC requirement - Update README.md
  README.md
Labels: Documentation

#1394 chore: Remove the BlockAcknowledgement block_already_exists response
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/BlockStreamProducerSession.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherServicePlugin.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/PublisherTest.java
  protobuf-sources/src/main/proto/block-node/api/block_stream_publish_service.proto
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamObserver.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/startup/SimulatorStartupData.java
  tools-and-tests/simulator/src/main/java/org/hiero/block/simulator/startup/impl/SimulatorStartupDataImpl.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/startup/impl/SimulatorStartupDataImplTest.java
  tools-and-tests/suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java
Labels: Simulator, Block Node, Publisher Plugin, Protobuf

#1393 feat: Create Simulator Test Framework with Fixtures
  tools-and-tests/simulator/build.gradle.kts
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/BlockStreamSimulatorTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/ConfigInjectionModuleTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/BlockAsFileBlockStreamManagerTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/GeneratorInjectionModuleTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/itemhandler/TransactionResultHandlerTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/ConsumerStreamGrpcClientImplTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/ConsumerStreamObserverTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcServerImplTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamServerObserverTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/metrics/MetricsInjectionModuleTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/metrics/MetricsServiceTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/mode/PublishClientManagerTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/mode/PublisherClientModeHandlerTest.java
  tools-and-tests/simulator/src/testFixtures/java/module-info.java
  tools-and-tests/simulator/src/testFixtures/java/org/hiero/block/simulator/fixtures/TestUtils.java
  tools-and-tests/simulator/src/testFixtures/java/org/hiero/block/simulator/fixtures/blocks/BlockBuilder.java
  tools-and-tests/simulator/src/testFixtures/java/org/hiero/block/simulator/fixtures/generator/TestBlockStreamManager.java
Labels: Simulator, pull request

#1400 chore: Standardize first 4 terminal code API responses
  README.md
  protobuf-sources/src/main/proto/block-node/api/block_access_service.proto
  protobuf-sources/src/main/proto/block-node/api/block_stream_publish_service.proto
  protobuf-sources/src/main/proto/block-node/api/block_stream_subscribe_service.proto
  protobuf-sources/src/main/proto/block-node/api/proof_service.proto
  protobuf-sources/src/main/proto/block-node/api/state_service.proto
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/mode/PublishClientManagerTest.java
Labels: Protobuf

#1402 test: Refactor wildcard imports in Simulator
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/data/BlockStreamConfigTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/data/UnorderedStreamConfigTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/types/GenerationModeTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/config/types/StreamingModeTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/BlockAsFileBlockStreamManagerTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/CraftBlockStreamManagerTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/generator/GeneratorInjectionModuleTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcServerImplTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamServerObserverTest.java
  tools-and-tests/simulator/src/test/java/org/hiero/block/simulator/mode/PublisherServerModeHandlerTest.java
Labels: pull request

#1421 feat(1370): Rebuild Stream Publisher for Finalized Protocol Support
  block-node/stream-publisher/build.gradle.kts
  block-node/stream-publisher/src/main/java/module-info.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/BlockStreamProducerSession.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/LiveStreamPublisherManager.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherConfig.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherHandler.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherServicePlugin.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/StreamPublisherManager.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/StreamPublisherPlugin.java
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/UpdateCallback.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/BlockStreamProducerSessionTest.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/PublisherConfigTest.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/PublisherHandlerTest.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/PublisherTest.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/fixtures/TestResponsePipeline.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/fixtures/TestStreamPublisherManager.java
  gradle/toolchain-versions.properties
  protobuf-sources/src/main/proto/block-node/api/block_stream_publish_service.proto
  protobuf-sources/src/main/proto/internal/unparsed.proto
  tools-and-tests/suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java
  tools-and-tests/suites/src/main/java/org/hiero/block/suites/verification/VerificationCommonTests.java
Labels: pull request

#1384 feat(backfill): Backfill Plugin - Part 1 Autonomous Flow
  block-node/app/build.gradle.kts
  block-node/app/src/main/resources/app.properties
  block-node/app/src/testFixtures/java/module-info.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/SimpleBlockRangeSet.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/SimpleInMemoryHistoricalBlockFacility.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/TestBlockMessagingFacility.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/server/TestBlockNodeServer.java
  block-node/backfill/build.gradle.kts
  block-node/backfill/src/main/java/module-info.java
  block-node/backfill/src/main/java/org/hiero/block/node/backfill/BackfillConfiguration.java
  block-node/backfill/src/main/java/org/hiero/block/node/backfill/BackfillGrpcClient.java
  block-node/backfill/src/main/java/org/hiero/block/node/backfill/BackfillPlugin.java
  block-node/backfill/src/main/java/org/hiero/block/node/backfill/client/BlockNodeClient.java
  block-node/backfill/src/main/java/org/hiero/block/node/backfill/client/BlockNodeServerStatusClient.java
  block-node/backfill/src/main/java/org/hiero/block/node/backfill/client/BlockNodeSubscribeClient.java
  block-node/backfill/src/main/java/org/hiero/block/node/backfill/client/proto/block_node_source.proto
  block-node/backfill/src/test/java/org/hiero/block/node/backfill/BackfillPluginTest.java
  block-node/backfill/src/test/resources/block-nodes-2.json
  block-node/backfill/src/test/resources/block-nodes-3.json
  block-node/backfill/src/test/resources/block-nodes.json
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPluginTest.java
  block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/BlocksFilesRecentPlugin.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileRecentPluginTest.java
  block-node/messaging/src/main/java/org/hiero/block/node/messaging/BlockMessagingFacilityImpl.java
  block-node/messaging/src/main/java/org/hiero/block/node/messaging/BlockNotificationRingEvent.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockMessagingFacilityExceptionTest.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockMessagingServiceBlockNotificationTest.java
  block-node/messaging/src/test/java/org/hiero/block/server/messaging/BlockNotificationRingEventTest.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/blockmessaging/BackfilledBlockNotification.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/blockmessaging/BlockMessagingFacility.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/blockmessaging/BlockNotificationHandler.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/blockmessaging/BlockSource.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/blockmessaging/PersistedNotification.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/blockmessaging/VerificationNotification.java
  block-node/verification/src/main/java/org/hiero/block/node/verification/BlockVerificationSession.java
  block-node/verification/src/main/java/org/hiero/block/node/verification/VerificationServicePlugin.java
  block-node/verification/src/test/java/org/hiero/block/node/verification/BlockVerificationSessionTest.java
  block-node/verification/src/test/java/org/hiero/block/node/verification/VerificationServicePluginTest.java
  hiero-dependency-versions/build.gradle.kts
  settings.gradle.kts
Labels: New Feature, Block Node

#1429 chore(release): Bump version to `0.16.0-SNAPSHOT`
  charts/block-node-server/Chart.yaml
  charts/blockstream-simulator/Chart.yaml
  version.txt
Labels: Release

#1436 test: Multi-Publisher Plugin Unit Tests - Interim PR
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/blocks/SimpleTestBlockItemBuilder.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/GrpcPluginTestBase.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/PluginTestBase.java
  block-node/backfill/src/test/java/org/hiero/block/node/backfill/BackfillPluginTest.java
  block-node/block-access/src/test/java/org/hiero/block/node/access/service/BlockAccessServicePluginTest.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPluginTest.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileRecentPluginTest.java
  block-node/s3-archive/src/test/java/org/hiero/block/node/archive/s3/S3ArchivePluginTest.java
  block-node/server-status/src/test/java/org/hiero/block/node/server/status/ServerStatusServicePluginTest.java
  block-node/stream-publisher/build.gradle.kts
  block-node/stream-publisher/src/main/java/org/hiero/block/node/stream/publisher/PublisherHandler.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/PublisherHandlerTest.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/StreamPublisherPluginTest.java
  block-node/stream-publisher/src/test/java/org/hiero/block/node/stream/publisher/fixtures/TestStreamPublisherManager.java
  block-node/stream-subscriber/src/test/java/org/hiero/block/node/stream/subscriber/SubscriberTest.java
  block-node/verification/src/test/java/org/hiero/block/node/verification/VerificationServicePluginTest.java
Labels: pull request
