Repository hiero-ledger/hiero-block-node, pull requests merged in 2025-04, with the labels that each got.

#913 docs: Create MAINTAINERS.md
  MAINTAINERS.md
Labels: Improvement

#938 chore: updated the codecov.yml for restricting excessive code coverage runs
  codecov.yml
Labels: CI/CD

#943 fix: Publisher plugin fixes and tests
  block-node/publisher/build.gradle.kts
  block-node/publisher/src/main/java/module-info.java
  block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java
  block-node/publisher/src/main/java/org/hiero/block/node/publisher/PublisherConfig.java
  block-node/publisher/src/main/java/org/hiero/block/node/publisher/PublisherServicePlugin.java
  block-node/publisher/src/main/java/org/hiero/block/node/publisher/UpdateCallback.java
  block-node/publisher/src/test/java/org/hiero/block/node/publisher/BlockStreamProducerSessionTest.java
  block-node/publisher/src/test/java/org/hiero/block/node/publisher/PublisherConfigTest.java
Labels: Block Node

#941 test: Files Recent Plugin Unit Tests
  block-node/block-providers/files.recent/build.gradle.kts
  block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/FilesRecentConfig.java
  block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/UnverifiedHandler.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/FilesRecentConfigTest.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/UnverifiedHandlerTest.java
  hiero-dependency-versions/build.gradle.kts
Labels: pull request

#940 test: UT for Verification Session
  block-node/verification/build.gradle.kts
  block-node/verification/src/test/java/org/hiero/block/node/verification/BlockVerificationSessionTest.java
  block-node/verification/src/test/resources/test-blocks/perf-10K-1731.blk.gz
Labels: Tests

#947 test: Files Recent Plugin Unit Tests Pt.2
  block-node/block-providers/files.recent/build.gradle.kts
  block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/BlockFileBlockAccessor.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileBlockAccessorTest.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/FilesRecentConfigTest.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/UnverifiedHandlerTest.java
  common/build.gradle.kts
  common/src/main/java/org/hiero/block/common/utils/Preconditions.java
  common/src/test/java/org/hiero/block/common/utils/PreconditionsTest.java
Labels: Block Provider

#950 fix: Add empty list handling for Publisher Session
  block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java
  block-node/publisher/src/main/java/org/hiero/block/node/publisher/PublisherServicePlugin.java
  block-node/publisher/src/test/java/org/hiero/block/node/publisher/BlockStreamProducerSessionTest.java
Labels: Block Node, Publisher Plugin

#961 chore(release): Bump versions for v0.9.0-SNAPSHOT
  charts/block-node-server/Chart.yaml
  charts/blockstream-simulator/Chart.yaml
  version.txt
Labels: Release

#953 chore: Improve PR Gradle Checks GHA definition in 505
  .github/workflows/pr-checks.yaml
Labels: github_actions

#958 test: Files Recent Plugin Unit Tests Pt.3
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/blocks/SimpleTestBlockItemBuilder.java
  block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/BlocksFilesRecentPlugin.java
  block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/UnverifiedHandler.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileBlockAccessorTest.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileRecentPluginTest.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/FilesRecentConfigTest.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/UnverifiedHandlerTest.java
Labels: pull request

#955 fix: e2e improvements
  .github/workflows/smoke-test.yaml
  suites/build.gradle.kts
  suites/src/main/java/module-info.java
  suites/src/main/java/org/hiero/block/suites/BaseSuite.java
  suites/src/main/java/org/hiero/block/suites/persistence/positive/PositiveDataPersistenceTests.java
Labels: Tests

#964 fix: Simulator Helm Chart Deployment in Consumer Mode
  charts/blockstream-simulator/templates/deployment.yaml
Labels: Bug, Simulator

#965 fix: Simulator Helm Chart Deployment in Consumer Mode (#964)
  .github/workflows/pr-checks.yaml
  charts/blockstream-simulator/templates/deployment.yaml
Labels: Bug

#970 chore: Add UTs for Recent BlockFileBlockAccessor exception handling
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileBlockAccessorTest.java
Labels: Tests

#842 feat: Add E2E Local Node Smart Contracts Workflow
  .github/workflows/local-node-test-reusable.yaml
  .github/workflows/local-node-test.yaml
Labels: CI/CD

#988 build(deps): Upgrading to pbjVersion `0.11.0` and swirldsVersion to `0.61.1`
  block-node/base/src/main/java/org/hiero/block/server/notifier/NotifierImpl.java
  block-node/base/src/main/java/org/hiero/block/server/producer/ProducerBlockItemObserver.java
  block-node/base/src/test/java/org/hiero/block/server/producer/ProducerBlockItemObserverTest.java
  block-node/base/src/test/java/org/hiero/block/server/util/PbjProtoTestUtils.java
  block-node/server/src/test/java/org/hiero/block/server/notifier/NotifierImplTest.java
  block-node/server/src/test/java/org/hiero/block/server/pbj/PbjBlockStreamServiceIntegrationTest.java
  block-node/server/src/test/java/org/hiero/block/server/util/PbjProtoTestUtils.java
  hiero-dependency-versions/build.gradle.kts
  stream/build.gradle.kts
Labels: dependencies

#989 ci: Change frequency of running LocalNode test GHA WF to just after merge
  .github/workflows/local-node-test.yaml
Labels: github_actions

#994 fix: Fix verification test pbj parse exception
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/blocks/BlockUtils.java
  block-node/app/src/testFixtures/resources/test-blocks/generated-10.blk.gz
  block-node/app/src/testFixtures/resources/test-blocks/perf-10K-1731.blk.gz
  block-node/app/src/testFixtures/resources/test-blocks/perf-10K-1731.blk.json
  block-node/verification/src/test/java/org/hiero/block/node/verification/BlockVerificationSessionTest.java
Labels: Bug, Tests

#996 test: Files Historic Plugin Unit Tests Pt 2
  block-node/base/build.gradle.kts
  block-node/base/src/main/java/org/hiero/block/node/base/CompressionType.java
  block-node/base/src/test/java/org/hiero/block/node/base/CompressionTypeTest.java
  block-node/block-providers/files.historic/build.gradle.kts
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlockPath.java
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/FilesHistoricConfig.java
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/ZipBlockAccessor.java
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchive.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlockPathTest.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/FilesHistoricConfigTest.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockAccessorTest.java
Labels: pull request

#998 fix: Update pr-formatting.yaml
  .github/workflows/pr-formatting.yaml
Labels: dependencies

#987 feat: added block stream simulator mid-block sending failure
  simulator/src/main/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializer.java
  simulator/src/main/java/org/hiero/block/simulator/config/data/BlockStreamConfig.java
  simulator/src/main/java/org/hiero/block/simulator/config/types/MidBlockFailType.java
  simulator/src/main/java/org/hiero/block/simulator/grpc/PublishStreamGrpcClient.java
  simulator/src/main/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImpl.java
  simulator/src/main/resources/app.properties
  simulator/src/test/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java
  simulator/src/test/java/org/hiero/block/simulator/config/logging/SimulatorConfigurationLoggerTest.java
  simulator/src/test/java/org/hiero/block/simulator/grpc/impl/PublishStreamGrpcClientImplTest.java
Labels: pull request

#1029 chore: Re-merge 1009 files historic plugin unit tests pt 3
  block-node/base/src/main/java/org/hiero/block/node/base/CompressionType.java
  block-node/base/src/test/java/org/hiero/block/node/base/CompressionTypeTest.java
  block-node/block-providers/files.historic/build.gradle.kts
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlockPath.java
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchive.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlockPathTest.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockAccessorTest.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchiveTest.java
Labels: pull request

#1028 chore: Re-merge Verification e2e tests
  simulator/src/main/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializer.java
  simulator/src/main/java/org/hiero/block/simulator/config/data/BlockGeneratorConfig.java
  simulator/src/main/java/org/hiero/block/simulator/config/data/ConsumerConfig.java
  simulator/src/main/java/org/hiero/block/simulator/generator/CraftBlockStreamManager.java
  simulator/src/main/resources/app.properties
  suites/src/main/java/org/hiero/block/suites/verification/BlockVerificationTestSuites.java
  suites/src/main/java/org/hiero/block/suites/verification/VerificationCommonTests.java
Labels: pull request

#1030 chore: Fix gradle baseline
  .github/workflows/support/scripts/generate-gradle-artifact-baseline.sh
Labels: CI/CD

#1034 chore(release): Bump versions for v0.10.0-SNAPSHOT
  charts/block-node-server/Chart.yaml
  charts/blockstream-simulator/Chart.yaml
  version.txt
Labels: Release

#1037 test: Failing UT for Simulator Config Mappings
  simulator/src/test/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java
  simulator/src/test/java/org/hiero/block/simulator/config/logging/SimulatorConfigurationLoggerTest.java
Labels: pull request

#1042 chore: Cherry-pick of #1040 into release branch `release/0.9`
  .github/workflows/release-push-image.yaml
Labels: Release, github_actions

#1040 fix: Fixing Publish Workflow
  .github/workflows/release-push-image.yaml
Labels: github_actions

#1061 chore: Removal of SmokeTests Artifacts and GHA WF
  .github/workflows/smoke-test.yaml
  block-node/app/src/test/resources/batch-consumers.sh
  block-node/app/src/test/resources/block_service.proto
  block-node/app/src/test/resources/consumer.sh
  block-node/app/src/test/resources/get-block.sh
  block-node/app/src/test/resources/producer.sh
  block-node/app/src/test/resources/remove-simulator-consumers.sh
  block-node/app/src/test/resources/smoke-test.sh
  block-node/app/src/test/resources/start-simulator-consumers.sh
  block-node/app/src/test/resources/templates/block_proof_template.json
  block-node/app/src/test/resources/templates/event_template.json
  block-node/app/src/test/resources/templates/header_template.json
  block-node/app/src/test/resources/test-blocks/hashing-01.blk.gz
Labels: github_actions, Tests

#1043 feat: Implement Cloud Archive Plugin
  block-node/app/build.gradle.kts
  block-node/app/src/main/java/org/hiero/block/node/app/BlockNodeApp.java
  block-node/app/src/main/java/org/hiero/block/node/app/config/ConfigLogger.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/blocks/SimpleTestBlockItemBuilder.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/GrpcPluginTestBase.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/PluginTestBase.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/SimpleInMemoryHistoricalBlockFacility.java
  block-node/archive/src/main/java/module-info.java
  block-node/archive/src/main/java/org/hiero/block/node/archive/ArchivePlugin.java
  block-node/base/build.gradle.kts
  block-node/base/src/main/java/module-info.java
  block-node/base/src/main/java/org/hiero/block/node/base/s3/S3Client.java
  block-node/base/src/main/java/org/hiero/block/node/base/s3/XmlBodyHandler.java
  block-node/base/src/main/java/org/hiero/block/node/base/tar/TaredBlockIterator.java
  block-node/base/src/test/java/org/hiero/block/node/base/s3/S3ClientTest.java
  block-node/base/src/test/java/org/hiero/block/node/base/tar/TaredBlockIteratorTest.java
  block-node/block-access/src/test/java/org/hiero/block/node/access/service/BlockAccessServicePluginTest.java
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/ZipBlockAccessor.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/ZipBlockArchiveTest.java
  block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/BlockFileBlockAccessor.java
  block-node/block-providers/files.recent/src/main/java/org/hiero/block/node/blocks/files/recent/BlocksFilesRecentPlugin.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileBlockAccessorTest.java
  block-node/block-providers/files.recent/src/test/java/org/hiero/block/node/blocks/files/recent/BlockFileRecentPluginTest.java
  block-node/publisher/src/test/java/org/hiero/block/node/publisher/PublisherTest.java
  block-node/s3-archive/build.gradle.kts
  block-node/s3-archive/src/main/java/module-info.java
  block-node/s3-archive/src/main/java/org/hiero/block/node/archive/s3/S3ArchiveConfig.java
  block-node/s3-archive/src/main/java/org/hiero/block/node/archive/s3/S3ArchivePlugin.java
  block-node/s3-archive/src/test/java/org/hiero/block/node/archive/s3/S3ArchivePluginTest.java
  block-node/spi/src/main/java/org/hiero/block/node/spi/historicalblocks/BlockAccessor.java
  block-node/spi/src/test/java/org/hiero/block/node/spi/historicalblocks/BlockAccessorTest.java
  block-node/subscriber/src/test/java/org/hiero/block/node/subscriber/SubscriberTest.java
  block-node/verification/src/test/java/org/hiero/block/node/verification/VerificationServicePluginTest.java
  hiero-dependency-versions/build.gradle.kts
Labels: Feature Enhancement

#1055 fix: hard shutdown of the producer causes exception when another is connected
  block-node/publisher/src/main/java/org/hiero/block/node/publisher/BlockStreamProducerSession.java
  suites/src/main/java/org/hiero/block/suites/BaseSuite.java
  suites/src/main/java/org/hiero/block/suites/block/access/GetBlockApiTests.java
  suites/src/main/java/org/hiero/block/suites/grpc/positive/PositiveEndpointBehaviourTests.java
  suites/src/main/java/org/hiero/block/suites/persistence/positive/PositiveDataPersistenceTests.java
  suites/src/main/java/org/hiero/block/suites/publisher/positive/PositiveMultiplePublishersTests.java
  suites/src/main/java/org/hiero/block/suites/utils/BlockAccessUtils.java
  suites/src/main/java/org/hiero/block/suites/utils/BlockSimulatorUtils.java
  suites/src/main/java/org/hiero/block/suites/verification/VerificationCommonTests.java
Labels: Tests, Publisher Plugin

#1058 feat: Create new stream subscriber plugin
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/GrpcPluginTestBase.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/SimpleInMemoryHistoricalBlockFacility.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/TestBlockMessagingFacility.java
  block-node/block-access/src/main/java/org/hiero/block/node/access/service/BlockAccessServicePlugin.java
  block-node/stream-subscriber/build.gradle.kts
  block-node/stream-subscriber/src/main/java/module-info.java
  block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/BlockStreamSubscriberSession.java
  block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberConfig.java
  block-node/stream-subscriber/src/main/java/org/hiero/block/node/stream/subscriber/SubscriberServicePlugin.java
  block-node/stream-subscriber/src/test/java/org/hiero/block/node/stream/subscriber/SubscriberTest.java
  settings.gradle.kts
Labels: Block Node, Subscriber Plugin

#966 feat: added block stream simulator out-of-order streaming
  simulator/src/main/java/org/hiero/block/simulator/config/ConfigInjectionModule.java
  simulator/src/main/java/org/hiero/block/simulator/config/SimulatorConfigExtension.java
  simulator/src/main/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializer.java
  simulator/src/main/java/org/hiero/block/simulator/config/data/UnorderedStreamConfig.java
  simulator/src/main/java/org/hiero/block/simulator/generator/CraftBlockStreamManager.java
  simulator/src/main/java/org/hiero/block/simulator/generator/GeneratorInjectionModule.java
  simulator/src/main/java/org/hiero/block/simulator/mode/impl/PublisherClientModeHandler.java
  simulator/src/main/java/org/hiero/block/simulator/startup/SimulatorStartupData.java
  simulator/src/main/java/org/hiero/block/simulator/startup/impl/SimulatorStartupDataImpl.java
  simulator/src/main/resources/app.properties
  simulator/src/test/java/org/hiero/block/simulator/config/ConfigInjectionModuleTest.java
  simulator/src/test/java/org/hiero/block/simulator/config/SimulatorMappedConfigSourceInitializerTest.java
  simulator/src/test/java/org/hiero/block/simulator/config/data/UnorderedStreamConfigTest.java
  simulator/src/test/java/org/hiero/block/simulator/config/logging/SimulatorConfigurationLoggerTest.java
  simulator/src/test/java/org/hiero/block/simulator/generator/CraftBlockStreamManagerTest.java
  simulator/src/test/java/org/hiero/block/simulator/generator/GeneratorInjectionModuleTest.java
  simulator/src/test/java/org/hiero/block/simulator/mode/PublisherClientModeHandlerTest.java
  simulator/src/test/java/org/hiero/block/simulator/startup/impl/SimulatorStartupDataImplTest.java
Labels: Simulator

#1064 test: Files Historic Plugin Unit Tests Pt. 5
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/async/BlockingSerialExecutor.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/NoOpServiceBuilder.java
  block-node/app/src/testFixtures/java/org/hiero/block/node/app/fixtures/plugintest/SimpleInMemoryHistoricalBlockFacility.java
  block-node/block-providers/files.historic/src/main/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPlugin.java
  block-node/block-providers/files.historic/src/test/java/org/hiero/block/node/blocks/files/historic/BlocksFilesHistoricPluginTest.java
Labels: pull request

#843 chore: remove block data from the repo
  simulator/build.gradle.kts
  simulator/docker/Dockerfile
  simulator/src/main/java/org/hiero/block/simulator/config/data/BlockGeneratorConfig.java
  simulator/src/main/resources/block-0.0.3.tar.gz
  simulator/src/test/java/org/hiero/block/simulator/BlockStreamSimulatorTest.java
  simulator/src/test/java/org/hiero/block/simulator/TestUtils.java
  simulator/src/test/java/org/hiero/block/simulator/config/data/BlockStreamConfigTest.java
  simulator/src/test/java/org/hiero/block/simulator/generator/BlockAsFileBlockStreamManagerTest.java
  simulator/src/test/java/org/hiero/block/simulator/generator/BlockAsFileLargeDataSetsTest.java
  simulator/src/test/java/org/hiero/block/simulator/generator/GeneratorInjectionModuleTest.java
  suites/src/main/resources/block-0.0.3/000000000000000000000000000000000001.blk.gz
  suites/src/main/resources/block-0.0.3/000000000000000000000000000000000002.blk.gz
  suites/src/main/resources/block-0.0.3/000000000000000000000000000000000003.blk.gz
  suites/src/main/resources/block-0.0.3/000000000000000000000000000000000004.blk.gz
  suites/src/main/resources/block-0.0.3/000000000000000000000000000000000005.blk.gz
Labels: pull request
